### ISSUE TITLE
SyntaxError in aws_autopilot_predict_outcome_response_translator

### ISSUE THREAD

**Issue by uchiyamaa** [aws-samples/amazon-sagemaker-integration-with-snowflake#31]
I have also created a machine learning model using my own data.

When I use the aws_autopilot_predict_outcome function, I get a SyntaxError like the following

select date, sum_usage,(parse_json(
aws_autopilot_predict_outcome(
'elec-weather-prediction-dev5'.
,array_construct().
Date, avg_temp, rainfall, sunshine hours, avg_hum))
): "predicted_label")::varchar predicted_label
From elec_data_test.

100132 (P0000): JavaScript execution error.Uncaught SyntaxError: AWS_AUTOPILOT_PREDICT_OUTCOME_RESPONSE_TRANSLATOR at '"body"' position 25 in JSON Unexpected number in JSON: 83445.7265625,79439.71875,78769.765625,78609.78125,82588.359375,90885.421875,88002.7265625,8215.609375,74566.484375,87935. 4765625,95866.5625,94939.046875,95336.25,96601.1015625,88641.6328125,83162.421875,90584.1640625,97482.046875,100302.7265625,100247. 765625,101484.875,90107.5078125,84487.171875,90363.2421875,95441.0859375,96502.046875,93007.2890625,94003.765625,88086. 7421875,85079.7890625,92339.453125,93635.6796875,93627.6953125,94696.9765625,95278.0859375,91584.1875,89055.3984375' position 22
stackstrace
AWS_AUTOPILOT_PREDICT_OUTCOME_RESPONSE_TRANSLATOR Number of lines: 11

This is probably happening because Sagemaker is returning an unexpected response.

**Comment by DerrickZhang123** [comment]
Hi uchiyamaa, 
This problem has been fixed. Please retrain your model and call the prediction api. 
Please let us know if you have any further issue. Thanks!

**Comment by maxkondra** [comment]
Closing this issue. Please feel free to re-open it if the problem persists.
